server:
  port: 8081

spring:
  web:
    cors:
      allowed-origins: "http://localhost:8081" # 허용할 도메인
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"   # 허용할 HTTP 메서드
      allowed-headers: "*"                    # 모든 헤더 허용
      allow-credentials: true                 # 쿠키 전달 허용
  datasource:
    url: jdbc:mysql://localhost:3306/mockcote?serverTimezone=Asia/Seoul
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: Asia/Seoul   # JSON 직렬화 시 시간대 설정
  mvc:
    format:
      date-time: yyyy-MM-dd'T'HH:mm:ss  # 날짜/시간 포맷 설정
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true         # SQL 보기 좋게 포맷
    open-in-view: false          # 성능 문제 방지 (권장 설정)

logging:
  level:
    root: info              # 전체 로깅 레벨 설정
#    mockcote: debug      # 패키지 별로 로그 레벨 설정 (예: 애플리케이션 패키지)
#    org.springframework: warn # 스프링 관련 로그는 경고 수준만 출력
#    org.hibernate.SQL: debug   # 실행되는 SQL 출력
#    org.hibernate.type: trace  # SQL 파라미터 값 출력 (개발 중 유용)

