server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mockcote_time?serverTimezone=Asia/Seoul
    username: ssafy
    password: ssafyssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: Asia/Seoul   # JSON 직렬화 시 시간대 설정
  mvc:
    format:
      date-time: yyyy-MM-dd'T'HH:mm:ss  # 날짜/시간 포맷 설정
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true         # SQL 보기 좋게 포맷
    open-in-view: false          # 성능 문제 방지 (권장 설정)

logging:
  level:
    root: info             # 전체 로깅 레벨 설정

statistics-service:
  url: http://localhost:8082 # 통계 서비스 히스토리 저장 요청 경로
